#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Mojo::Server;
use Mojo::Log;

my $app  = Mojo::Server->new->build_app('MyApp');
my $path = '/var/log';
if (-w $path) {
  my $log = Mojo::Log->new(path => "$path/mojo.log", level => 'trace');
  $app->log($log);
} else {
  warn "Path: $path is not writable\n";
}

$app->start;
